Repository cpp-gamedev/facade, pull requests merged in 2022-10, with the labels that each got.

#24 Update the fly camera controls.
  src/main.cpp
Labels: enhancement

#53 Misc improvements
  CMakeLists.txt
  lib/CMakeLists.txt
  lib/engine/CMakeLists.txt
  lib/engine/include/facade/engine/editor/inspector.hpp
  lib/engine/include/facade/engine/engine.hpp
  lib/engine/src/build_version.hpp.in
  lib/engine/src/editor/inspector.cpp
  lib/engine/src/engine.cpp
  lib/scene/include/facade/scene/load_status.hpp
  lib/scene/include/facade/scene/scene.hpp
  lib/scene/src/detail/gltf.cpp
  lib/scene/src/detail/gltf.hpp
  lib/scene/src/scene.cpp
  lib/util/CMakeLists.txt
  lib/util/include/facade/util/version.hpp
  src/main.cpp
Labels: enhancement, imgui

#49 Working on comments
  lib/engine/src/engine.cpp
  lib/glfw/include/facade/glfw/glfw.hpp
  lib/glfw/include/facade/glfw/glfw_wsi.hpp
  lib/glfw/include/facade/glfw/input.hpp
  lib/render/include/facade/render/gui.hpp
  lib/render/include/facade/render/renderer.hpp
  lib/render/src/renderer.cpp
  lib/scene/CMakeLists.txt
  lib/scene/include/facade/scene/camera.hpp
  lib/scene/include/facade/scene/fly_cam.hpp
  lib/scene/include/facade/scene/id.hpp
  lib/scene/include/facade/scene/lights.hpp
  lib/scene/include/facade/scene/load_status.hpp
  lib/scene/include/facade/scene/material.hpp
  lib/scene/include/facade/scene/node.hpp
  lib/scene/include/facade/scene/node_data.hpp
  lib/scene/include/facade/scene/rect.hpp
  lib/scene/include/facade/scene/scene.hpp
  lib/scene/src/detail/gltf.hpp
  lib/scene/src/scene.cpp
  lib/scene/src/transform.cpp
  lib/util/CMakeLists.txt
  lib/util/include/facade/util/byte_buffer.hpp
  lib/util/include/facade/util/colour_space.hpp
  lib/util/include/facade/util/data_provider.hpp
  lib/util/include/facade/util/enum_array.hpp
  lib/util/include/facade/util/error.hpp
  lib/util/include/facade/util/fixed_string.hpp
  lib/util/include/facade/util/flex_array.hpp
  lib/util/include/facade/util/image.hpp
  lib/util/include/facade/util/logger.hpp
  lib/util/include/facade/util/nvec3.hpp
  lib/util/include/facade/util/pinned.hpp
  lib/util/include/facade/util/ptr.hpp
  lib/util/include/facade/util/time.hpp
  lib/util/include/facade/util/transform.hpp
  lib/util/include/facade/util/type_id.hpp
  lib/util/include/facade/util/unique.hpp
  lib/util/include/facade/util/unique_task.hpp
  lib/util/include/facade/util/visitor.hpp
  lib/vk/CMakeLists.txt
  lib/vk/include/facade/vk/buffer.hpp
  lib/vk/include/facade/vk/defer.hpp
  lib/vk/include/facade/vk/defer_queue.hpp
  lib/vk/include/facade/vk/gfx.hpp
  lib/vk/include/facade/vk/pipes.hpp
  lib/vk/include/facade/vk/render_frame.hpp
  lib/vk/include/facade/vk/rotator.hpp
  lib/vk/include/facade/vk/swapchain.hpp
  lib/vk/include/facade/vk/wsi.hpp
  src/main.cpp
Labels: documentation, good first issue, Large Issue
